Importing libraries

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
SEED_VAL = 0
tf.__version__
tf.random.set_seed(SEED_VAL)

In [10]:
from ucimlrepo import fetch_ucirepo

# fetch dataset
rice_cammeo_and_osmancik = fetch_ucirepo(id=545)

# data (as pandas dataframes), let's convert to numpy
X = rice_cammeo_and_osmancik.data.features.to_numpy()
y_raw = rice_cammeo_and_osmancik.data.targets.to_numpy()

### Converting y to a 1D array and Encode it.

In [11]:
y = y_raw.ravel()
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

## Splitting the dataset into the Training and Test sets

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

## Feature Scaling
we scale the features so they're in the same range

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Building the ANN

### Initializing the ANN

In [14]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [15]:
ann.add(tf.keras.layers.Dense(units=16, activation='relu'))

### Adding the second hidden layer

In [16]:
ann.add(tf.keras.layers.Dense(units=8, activation='relu'))

### Adding the output layer

In [17]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Training The ANN

### Compiling the ANN

In [18]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [19]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100, shuffle=False)

Epoch 1/100
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7245 - loss: 0.6383
Epoch 2/100
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9155 - loss: 0.3299
Epoch 3/100
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9157 - loss: 0.2300
Epoch 4/100
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9156 - loss: 0.2094
Epoch 5/100
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9164 - loss: 0.2051
Epoch 6/100
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9173 - loss: 0.2037
Epoch 7/100
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9162 - loss: 0.2029
Epoch 8/100
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9160 - loss: 0.2024
Epoch 9/100
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9166 - loss: 0.2020
Epoch 10/100
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9179 - loss: 0.2016
Epoch 11/100
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9183 - loss: 0.2013
Epoch 12/100
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy:

## Model Predictions and Evaluations

### Predicting Insample test results

In [21]:
y_pred_ins = ann.predict(X_train)
y_pred_ins = (y_pred_ins > 0.5).astype("int")

90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


In [22]:
# Getting the accuracy score
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_train, y_pred_ins)
print(cm)
accuracy_score(y_train, y_pred_ins)

[[1106  111]
 [  96 1544]]


0.9275463773188659

### Out-Sample Prediction

In [23]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5).astype("int")
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 894us/step
[[1 1]
 [0 0]
 [0 1]
 ...
 [0 0]
 [0 1]
 [1 1]]


In [24]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[374  39]
 [ 23 517]]


0.9349422875131165