# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__
tf.random.set_seed(42)

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
# dataset = pd.read_csv('Social_Network_Ads.csv')
# X = dataset.iloc[:, :-1].values
# y = dataset.iloc[:, -1].values
#!pip install ucimlrepo

from ucimlrepo import fetch_ucirepo

# fetch dataset
rice_cammeo_and_osmancik = fetch_ucirepo(id=545)

# data (as pandas dataframes)
X = rice_cammeo_and_osmancik.data.features.to_numpy()
y = rice_cammeo_and_osmancik.data.targets.to_numpy()


# dataset = pd.read_csv('Churn_Modelling.csv')
# X = dataset.iloc[:, 3:-1].values
# y = dataset.iloc[:, -1].values

In [4]:
print(X.shape)
print(y)

(3810, 7)
[['Cammeo']
 ['Cammeo']
 ['Cammeo']
 ...
 ['Osmancik']
 ['Osmancik']
 ['Osmancik']]


In [5]:
print(y)

[['Cammeo']
 ['Cammeo']
 ['Cammeo']
 ...
 ['Osmancik']
 ['Osmancik']
 ['Osmancik']]


# Encoding the Y column

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
print("y before encoding")
print (y)
y = y.ravel()  # or do .reshape(-1) to convert to a 1D array

y = le.fit_transform(y)
print("y after encoding")
print (y)

mj = le.inverse_transform([0,0,1])
print(mj)

y before encoding
[['Cammeo']
 ['Cammeo']
 ['Cammeo']
 ...
 ['Osmancik']
 ['Osmancik']
 ['Osmancik']]
y after encoding
[0 0 0 ... 1 1 1]
['Cammeo' 'Cammeo' 'Osmancik']


In [7]:
print(y[0:3])
print(y[-1])

[0 0 0]
1


### Encoding categorical data

Label Encoding the "Gender" column

In [8]:
# from sklearn.preprocessing import LabelEncoder
# le = LabelEncoder()
# X[:, 2] = le.fit_transform(X[:, 2])

In [9]:
print(X)

[[1.52310000e+04 5.25578979e+02 2.29749878e+02 ... 9.28882003e-01
  1.56170000e+04 5.72895527e-01]
 [1.46560000e+04 4.94311005e+02 2.06020065e+02 ... 8.95404994e-01
  1.50720000e+04 6.15436316e-01]
 [1.46340000e+04 5.01122009e+02 2.14106781e+02 ... 9.12118077e-01
  1.49540000e+04 6.93258822e-01]
 ...
 [1.24370000e+04 4.42498993e+02 1.83572922e+02 ... 8.81144345e-01
  1.26450000e+04 6.26738548e-01]
 [9.88200000e+03 3.92296997e+02 1.61193985e+02 ... 8.74406099e-01
  1.00970000e+04 6.59063637e-01]
 [1.14340000e+04 4.04709992e+02 1.61079269e+02 ... 8.25692177e-01
  1.15910000e+04 8.02949429e-01]]


One Hot Encoding the "Geography" column

In [10]:
# from sklearn.compose import ColumnTransformer
# from sklearn.preprocessing import OneHotEncoder
# ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
# X = np.array(ct.fit_transform(X))

### Splitting the dataset into the Training set and Test set

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [13]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [14]:
ann.add(tf.keras.layers.Dense(units=16, activation='relu'))

### Adding the second hidden layer

In [15]:
ann.add(tf.keras.layers.Dense(units=8, activation='relu'))

### Adding the output layer

In [16]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [17]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [18]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100, shuffle=False)

Epoch 1/100
96/96 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7054 - loss: 0.5740
Epoch 2/100
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9157 - loss: 0.2751
Epoch 3/100
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9267 - loss: 0.2010
Epoch 4/100
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9259 - loss: 0.1884
Epoch 5/100
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9266 - loss: 0.1858
Epoch 6/100
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9267 - loss: 0.1849
Epoch 7/100
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9268 - loss: 0.1845
Epoch 8/100
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9268 - loss: 0.1842
Epoch 9/100
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9270 - loss: 0.1840
Epoch 10/100
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9270 - loss: 0.1839
Epoch 11/100
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9275 - loss: 0.1838
Epoch 12/100
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy:

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Solution**

In [19]:
single_test = X[4]
print(single_test)
predicted_class = (ann.predict(sc.transform([X[4]])) > 0.5).astype("int")
predicted_label = le.inverse_transform(predicted_class)[0]
print("predicted class and label: ", predicted_class, predicted_label)


[1.46880000e+04 5.07166992e+02 2.11743378e+02 8.93124542e+01
 9.06690896e-01 1.52620000e+04 6.46023929e-01]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step
predicted class and label:  [[0]] Cammeo


C:\Python311\Lib\site-packages\sklearn\preprocessing\_label.py:153: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

# Predicting Insample test results

In [20]:
y_pred_ins = ann.predict(X_train)
y_pred_ins = (y_pred_ins > 0.5).astype("int")

96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


In [24]:
# Getting the accuracy score
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_train, y_pred_ins)
print(cm)
accuracy_score(y_train, y_pred_ins)

[[1185  108]
 [  97 1658]]


0.9327427821522309

### Predicting the Test set results

In [22]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5).astype("int")
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step 
[[1 1]
 [0 0]
 [0 1]
 ...
 [0 0]
 [1 1]
 [0 0]]


### Making the Confusion Matrix

In [23]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[307  30]
 [ 22 403]]


0.931758530183727